<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body><table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="thwecmf_template_wrapper"><tr><td align="center" class="thwecmf-template-wrapper-column" valign="top" style="background-color: #f7f7f7; padding: 70px 0;" bgcolor="#f7f7f7"><table id="tpf_t_builder" width="600" cellspacing="0" cellpadding="0" class="thwecmf-main-builder thwecmf-template-block" style="max-width: 600px; width: 600px; margin: auto;" align="center"><tr><td class="thwecmf-builder-column" style="vertical-align: top; border-radius: 2px; background-size: cover; background-repeat: no-repeat; background-position: top; border-style: solid; border-color: #dedede; background-color: #fff; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; background-image: none;" bgcolor="#fff">
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1001" cellpadding="0" cellspacing="0px" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;" width="100%" align="center" bgcolor="transparent"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1002" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; padding-top: 36px; padding-right: 48px; padding-bottom: 36px; padding-left: 48px; text-align: center; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: #96588a;" width="100%" align="center" bgcolor="#96588a"><table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1003" cellspacing="0" cellpadding="0" style='table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #fff; font-size: 30px; line-height: 150%; font-weight: normal; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;' width="100%" align="center"><tr style='color: #fff; font-size: 30px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
<td class="thwecmf-block-child thwecmf-block-text-holder" style='vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #fff; font-size: 30px; font-weight: normal; line-height: 150%; text-align: left; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' align="left" bgcolor="transparent">
			<div class="wecmf-txt-wrap" style='color: #fff; font-size: 30px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>Sorry, your order was unsuccessful<br style='color: #fff; font-size: 30px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
</div>
			</td>
		</tr></table></td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1004" cellpadding="0" cellspacing="0px" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;" width="100%" align="center" bgcolor="transparent"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1005" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; padding-top: 48px; padding-right: 48px; padding-bottom: 0px; padding-left: 48px; text-align: left; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;" width="100%" align="left" bgcolor="transparent">
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1006" cellspacing="0" cellpadding="0" style='table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 14px; line-height: 150%; font-weight: normal; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;' width="100%" align="center"><tr style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
<td class="thwecmf-block-child thwecmf-block-text-holder" style='vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; text-align: left; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 0px; padding-bottom: 15px; padding-left: 0px;' align="left" bgcolor="transparent">
			<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>Hi <?php if(isset($order)) : ?><?php echo esc_html($order->get_billing_first_name()); ?><?php elseif(isset($user_login)): ?><?php echo esc_html($user_login); ?><?php endif; ?>,<br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
</div>
<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'><br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'></div>
<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>Unfortunately, we couldn't complete your order due to an issue with your payment method.<br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
</div>
<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'><br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'></div>
<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>If you'd like to continue with your purchase, please return to <a class="thwec-placeholder-site-name" rel="nofollow" href="#" style="text-decoration:none;color:inherit;"><?php echo esc_html( get_bloginfo() );?></a> and try a different method of payment.<br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
</div>
<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'><br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'></div>
<div class="wecmf-txt-wrap" style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>Your order details are as follows:<br style='color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
</div>
			</td>
		</tr></table>
<div class="thwecmf-hook-order-details"><?php if(isset($order)){ 
 					do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email ); 
 				}?></div>
<?php if(isset($order)){ 
  					do_action('woocommerce_email_after_order_table', $order, $sent_to_admin, $plain_text, $email); 
  				}?>
<?php if(isset($order)){ 
  					do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email ); 
  				}?>
<?php if(isset($order)){ 
  					do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email ); 
  				}?>
</td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1011" cellpadding="0" cellspacing="0px" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;" width="100%" align="center" bgcolor="transparent"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1012" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; padding-top: 0px; padding-right: 48px; padding-bottom: 48px; padding-left: 48px; text-align: center; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; background-image: none; background-color: transparent;" width="100%" align="center" bgcolor="transparent"><table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1013" cellspacing="0" cellpadding="0" style='table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 13px; line-height: 150%; font-weight: normal; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: center;' width="100%" align="center"><tr style='color: #636363; font-size: 13px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
<td class="thwecmf-block-child thwecmf-block-text-holder" style='vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 13px; font-weight: normal; line-height: 150%; text-align: center; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 15px; padding-right: 0px; padding-bottom: 15px; padding-left: 0px;' align="center" bgcolor="transparent">
			<div class="wecmf-txt-wrap" style='color: #636363; font-size: 13px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'><a class="thwec-placeholder-site-name" rel="nofollow" href="#" style="text-decoration:none;color:inherit;"><?php echo esc_html( get_bloginfo() );?></a><br style='color: #636363; font-size: 13px; font-weight: normal; line-height: 150%; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif;'>
</div>
			</td>
		</tr></table></td></tr></table>
</td></tr></table></td></tr></table></body>
</html>
